feat: make dispose support disposing instance of useFactory
opensumi/di pull request #116
Opened 2023-11-11 12:31 UTC by zhangpanweb

处理 https://github.com/opensumi/di/issues/111

处理方式：把 instance 挂在 creator 上， 形式为一个 `Set` ，当 creator dispose 时，重置 `creator.instance`

同时解决以下问题：
- `useFactory` 在 `dispose` 时 instance 无法被删除
- 在之前的情况下 `class provider` 为多例模式时， `dispose` 不会被调用。更新后， 多例的 `class provider` 被 `dispose` 时，其所有实例的 `dispose` 方法都会被调用
- `hasInstance` 无法判别 `useFactory`， 更新后，`useFactory` 的返回值，也可以通过 `hasInstance` 来进行判别。且多例 `class provider` 的 `instance` 同样可以被判别。

2023-11-11 12:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opensumi/di?pullRequest=116) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opensumi/di?pullRequest=116) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opensumi/di?pullRequest=116) it.</sub>

2023-11-13 02:48 UTC, bytemain requested changes

2023-11-13 02:48 UTC, bytemain commented on src/declare.ts
> +  instance?: Set<any>;
这个想法很好，这样一来确实解决了 instance 存哪儿的问题。但这样一个 set 是 Breaking change，我来看看有没有什么好方案，直接在这个 pr 上改一下了

2023-11-13 02:48 UTC, bytemain commented on src/declare.ts
> +  instance?: Set<any>;
我来改下就好

2023-11-13 02:49 UTC, bytemain commented on src/injector.ts
> +  onceInstanceDisposed(creator: InstanceCreator, cb: () => void) {
这里的入参最好还是用 instance

2023-11-13 02:50 UTC, bytemain commented on src/injector.ts
> +    creator.instance = new Set([value]);
这里应该存的是 applyHooks 后的 instance

2023-11-13 02:51 UTC, bytemain commented on src/injector.ts
> -      __id: id,
如果这个 pr 的内容发成 2.0，我们就移除掉这个 __id 字段

2023-11-13 02:55 UTC, zhangpanweb commented on src/declare.ts
> +  instance?: Set<any>;
creator 我理解不是一个内部变量么，这个有哪里暴露给外部了么？下面 __id 这个也一样

2023-11-13 03:09 UTC, bytemain commented on src/declare.ts
> +  instance?: Set<any>;
目前类型上啥设置的都是 public 的

2023-12-03 08:54 UTC, merged