WIP: Release 2.0.0
opensumi/di pull request #117
Opened 2023-12-03 08:54 UTC by bytemain

2023-12-05 02:43 UTC, erha19 commented on src/injector.ts
> +    return creator.instances!.values().next().value;
这里类型太严格，感觉可能会报错

2023-12-05 02:44 UTC, erha19 requested changes

2023-12-05 02:44 UTC, erha19 commented on test/decorators/hooks.test.ts
> +    it("hook's priority should work case1", async () => {
应该用单引号统一格式

2023-12-05 02:44 UTC, erha19 commented on test/decorators/hooks.test.ts
>    it('子injector应该正确拦截', () => {
2.0 可以顺带优化一下这些 test case 命名

2023-12-05 02:45 UTC, bytemain commented on test/decorators/hooks.test.ts
> +    it("hook's priority should work case1", async () => {
这个字符串内有个单引号，所以 format 工具自动变成双引号了

2023-12-14 02:31 UTC, bytemain commented
待补充文档：集成方需要自行引用 reflect metadata

2024-01-19 06:29 UTC, erha19 approved these changes
LGTM

2024-01-19 06:33 UTC, merged